// KH_LCNT
curl -OJX GET http://localhost:3000/api/document/docx/generate/019e9396-d6eb-701c-a61d-98d924183f05


// KQ_KH_LCNT TV
curl -OJX GET http://localhost:3000/api/document/docx/generate/019e939c-ba65-764d-8038-cdd610804e0d?type=decision

// KQ_KH_LCNT TT
curl -OJX GET http://localhost:3000/api/document/docx/generate/019e939c-ba77-722a-ad9d-eaf7078206a3