# desktop
curl -X GET http://localhost:3000/api/document/decision/019d916e-1df7-708a-aca2-cb40988705da/KH_LCNT

# laptop
curl -X GET http://localhost:3000/api/document/decision/019d809f-122e-77a8-ae52-2dd6998ff23a/KH_LCNT